=== fastapi/full-stack-fastapi-template/backend/contractguard/schemas/diff_report.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "DiffReportEntry",
  "type": "object",
  "required": ["endpoint", "method", "change_type", "breaking", "severity", "detected_at"],
  "properties": {
    "endpoint": { "type": "string", "example": "/items/{id}" },
    "method": { "type": "string", "enum": ["GET", "POST", "PUT", "DELETE", "PATCH"] },
    "change_type": {
      "type": "string",
      "enum": ["field_renamed", "field_type_changed", "field_added_required", "field_removed", "endpoint_removed"]
    },
    "breaking": { "type": "boolean" },
    "old_schema_fragment": { "type": "object" },
    "new_schema_fragment": { "type": "object" },
    "severity": { "type": "string", "enum": ["high", "medium", "low"] },
    "detected_at": { "type": "string", "format": "date-time" }
  }
}

=== fastapi/full-stack-fastapi-template/backend/contractguard/reports/diff_report_field_renamed.json
[
  {
    "endpoint": "/chat",
    "method": "POST",
    "change_type": "field_renamed",
    "breaking": true,
    "old_schema_fragment": {
      "answer": "string"
    },
    "new_schema_fragment": {
      "response_text": "string"
    },
    "severity": "high",
    "detected_at": "2026-09-26T12:32:56.064254+00:00"
  }
]

=== fastapi/full-stack-fastapi-template/backend/contractguard/reports/diff_report_endpoint_removed.json
[
  {
    "endpoint": "/api/v1/items/{id}",
    "method": "DELETE",
    "change_type": "endpoint_removed",
    "breaking": true,
    "old_schema_fragment": {
      "message": "string"
    },
    "new_schema_fragment": {},
    "severity": "high",
    "detected_at": "2026-09-26T17:00:02.339502+00:00"
  }
]

=== fastapi/full-stack-fastapi-template/backend/contractguard/reports/diff_report_type_changed.json
[
  {
    "endpoint": "/api/v1/items/",
    "method": "POST",
    "change_type": "field_type_changed",
    "breaking": true,
    "old_schema_fragment": {
      "description": "string"
    },
    "new_schema_fragment": {
      "description": "array"
    },
    "severity": "high",
    "detected_at": "2026-09-26T17:00:00.789863+00:00"
  },
  {
    "endpoint": "/api/v1/items/{id}",
    "method": "GET",
    "change_type": "field_type_changed",
    "breaking": true,
    "old_schema_fragment": {
      "description": "string"
    },
    "new_schema_fragment": {
      "description": "array"
    },
    "severity": "high",
    "detected_at": "2026-09-26T17:00:00.789863+00:00"
  },
  {
    "endpoint": "/api/v1/items/{id}",
    "method": "PUT",
    "change_type": "field_type_changed",
    "breaking": true,
    "old_schema_fragment": {
      "description": "string"
    },
    "new_schema_fragment": {
      "description": "array"
    },
    "severity": "high",
    "detected_at": "2026-09-26T17:00:00.789863+00:00"
  }
]
